[toolchain]
anchor_version = "0.28.0"  # Specify the Anchor version

[features]
seeds = true  # Enable seed derivation
instruction-data = true  # Allow custom instruction data
event-cpi = true  # Enable tracking program-derived events
resolution = true
skip-lint = false

[programs]
localnet = "7JYPt6XXmADUzAG12ZM3763PuF7XhJmfr7oWV9g2VrcM"
devnet = "7JYPt6XXmADUzAG12ZM3763PuF7XhJmfr7oWV9g2VrcM"
mainnet = "7JYPt6XXmADUzAG12ZM3763PuF7XhJmfr7oWV9g2VrcM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test:supply = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/supply-chain.ts"
test:integration = "yarn run ts-mocha -p ./tsconfig.json -t 2000000 tests/integration/**/*.ts"
deploy:devnet = "anchor deploy --provider.cluster devnet"
deploy:mainnet = "anchor deploy --provider.cluster mainnet"
migrate = "ts-node scripts/migrations/deploy.ts"
initialize = "ts-node scripts/initialize-program.ts"

[workspace]
members = ["programs/retailchain"]
types = "./target/types"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# These accounts will be copied into the test validator when it starts
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"  # SPL Token Program

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  # Metaplex Token Metadata Program